---
- name: Build disk
  hosts: ec2
  user: admin
  become: True
  gather_facts: false
  tasks:
    - name: run apt-get update and install python
      raw: "{{ item }}"
      loop:
        - sudo apt-get update
        - sudo apt-get -y install python
      become: true
      ignore_errors: true
  roles:
    - build-disk
